### PR TITLE
Local sensitivity analysis

### PR DESCRIPTION
**Pull request by NicolasDumoulin**
Hi,

Here is our proposition of local sensitivity analysis according to (Heijungs, 2010) method.
Please, let us know if it is the good way after reviewing.

Thanks 

(Heijungs, 2010) http://link.springer.com/article/10.1007%2Fs11367-010-0158-5

### CODE REVIEW

**Comment by msrocka** [comment]
I think it would be better if this could go into a separate class like `SensitivityCalculator` with a method `calculateLocalResult` and the `LcaCalculater` could remain unchanged. It could call the `LcaCalculator` internally to get the contribution result (it could swap the fields to the `LSAResult`, this would be not much overhead). It would also better to change the name of the result type from `LSAResult` to `LocalSensitivityResult` and the variable names and getters for `rscA` and `rscB` to `techCoefficients` and `enviCoefficients` as it would make the code easier to read.

**Comment by NicolasDumoulin** [comment]
Good suggestions :-)

**Comment by NicolasDumoulin** [comment]
looks better? :-)

**Comment by msrocka** [comment]
Hi Nicolas,
I created the separate branch as discussed: sensitivity-calc. When you send this pull request to this branch I will merge it.
Many thanks

**Comment by NicolasDumoulin** [comment]
New pull request created for the dedicated branch.
Thanks

**Pull request closed without merging**
