### PR TITLE
Apply both normalization and weighting factors when called on IPC

### PR DESCRIPTION
**Pull request by dr0nius**
IPC method result/total-impacts/weighted returns normalized + weighted impacts

### CODE REVIEW

**Comment by msrocka** [comment]
I agree, it should apply the normalization and weighting values in case normalization values are present. I think we do not need an additional method because this is what should be done here. It should just call `NwSetTable.apply` instead of `NwSetTable.weight`. Also `NwSetTable.weight` could be maybe removed, as it should always apply normalization values first when they are present.

**Comment by dr0nius** [comment]
Sounds good, updated the PR accordingly

**Comment by msrocka** [comment]
good, I would keep `getWeightedImpacts` as name because when there are no normalization factors (which is rarely the case but still possible) the method only applies the weighting factors; and when there are normalization values, they are applied first.

**Comment by dr0nius** [comment]
Corrected naming

**Pull request merged**
